In [1]:
import numpy as np
import pandas as pd
import math 
from pymoo.factory import get_problem

from pymoo.interface import crossover
from pymoo.factory import get_crossover
from pymoo.interface import mutation
from pymoo.factory import get_mutation

pf = get_problem("truss2d").pareto_front()
phi1= pf[:,0].reshape(-1,1)
phi2= pf[:,1].reshape(-1,1)
m =pf.shape[0]
print(phi1)
print(phi2)

[[0.004     ]
 [0.00404076]
 [0.00408152]
 ...
 [0.05125235]
 [0.05131968]
 [0.05138701]]
[[100000.        ]
 [ 98991.22689126]
 [ 98002.60298646]
 ...
 [  8437.34734651]
 [  8435.03206743]
 [  8432.74042712]]


In [2]:
def select_mating_pool(pop, fitness, num_parents):

    # Selecting the best individuals in the current generation as parents for producing the offspring of the next generation.

    parents = np.empty((num_parents, pop.shape[1]))

    for parent_num in range(num_parents):

        min_fitness_idx = np.where(fitness == np.min(fitness))

        min_fitness_idx = min_fitness_idx[0][0]

        parents[parent_num, :] = pop[min_fitness_idx, :]

        fitness[min_fitness_idx] = 99999

    return parents

In [3]:
def fitness(b1,b2,d):
    fitness_pop = np.empty([pop_size,1])
    fitness_pop[:]=np.nan
    
    for i in range(pop_size):

        d= d.astype(int)
        c  = np.array((phi1**b1[i])*(phi2**b2[i]))
        X  =((c.max()-c.min())/d[i])


        y=np.full((d[i],1100), np.nan)
        for j in range(d[i]-1):
            y[j,:c[np.logical_and(c>=j*X+c.min(),c<(j+1)*X+c.min())].size]=c[np.logical_and(c>=j*X+c.min(),c<(j+1)*X+c.min())]
        y[d[i]-1,:c[np.logical_and(c>=(d[i]-1)*X+c.min(),c<=c.max())].size]=c[np.logical_and(c>=(d[i]-1)*X+c.min(),c<=c.max())]
        
        p=np.copy(y)



        import math
        C_=0
        U_=0

        count1= np.count_nonzero(~np.isnan(p[0]))
        if count1<= math.floor(1100/d[i]) :
            U_=U_+count1
        else :
            C_=C_+1

        for k in range (1,d[i]):
            count= np.count_nonzero(~np.isnan(p[k]))
            count_=np.count_nonzero(~np.isnan(p[k-1]))

            if count<= math.floor(1100/d[i]) :
                U_=U_+count
            elif count_<=math.floor(1100/d[i]) :
                C_=C_+1
            else:
                p[k][count:count+count_]=p[k-1][:count_]
                p[k-1]= np.full((1,1100), np.nan)

        p.sort(axis=1)

        p=pd.DataFrame(p)
        e=p.isnull().all(axis=1)

        for l in range(d[i]):
            if e[l]==True:
                p=p.drop([l])

        p=p.to_numpy()
        h=p.shape[0]


        _cv=np.full((1,h),np.nan)
        for m in range(h):
            count = np.count_nonzero(~np.isnan(p[m]))
            if count> math.floor(1100/d[i]) :
                _cv[0][m]= (100*np.nanstd(p[m]))/np.nanmean(p[m])
            else:
                _cv[0][m] = 0

        #fitness
        if U_!=0:
            fitness_pop[i] = (C_+U_+np.nansum(_cv))+1000
        else:
            fitness_pop[i] = (C_+U_+np.nansum(_cv))

    return fitness_pop

In [4]:
import random
pop_size=100
d=random.randint(1,1100)
b2=random.random()
pop= np.empty([pop_size,3])
for i in range(pop_size):
    pop[i][0]=random.random()
    pop[i][1]=random.random()
    pop[i][2]=random.randint(1,1100)
    
for i in range(pop_size):
    if pop[i][0]>=pop[i][1]:
        pop[i][1]=pop[i][1]/pop[i][0]
        pop[i][0]=1
    else:
        pop[i][0]=pop[i][0]/pop[i][1]
        pop[i][1]=1
print(pop)

[[1.00000000e+00 9.45032531e-01 6.68000000e+02]
 [1.72749698e-01 1.00000000e+00 1.04000000e+03]
 [1.00000000e+00 4.67473813e-01 8.70000000e+01]
 [1.00000000e+00 5.10098025e-01 4.71000000e+02]
 [1.00000000e+00 8.89238119e-01 4.55000000e+02]
 [6.16067084e-01 1.00000000e+00 5.23000000e+02]
 [1.00000000e+00 4.55833176e-01 4.54000000e+02]
 [1.42116623e-01 1.00000000e+00 7.02000000e+02]
 [7.08767706e-01 1.00000000e+00 9.57000000e+02]
 [5.90896745e-01 1.00000000e+00 9.13000000e+02]
 [2.77810247e-01 1.00000000e+00 1.02200000e+03]
 [5.38861224e-01 1.00000000e+00 9.01000000e+02]
 [1.00000000e+00 2.17158638e-01 4.56000000e+02]
 [7.77179923e-01 1.00000000e+00 1.01200000e+03]
 [2.58728049e-01 1.00000000e+00 7.12000000e+02]
 [5.90934046e-01 1.00000000e+00 1.05900000e+03]
 [1.56329884e-01 1.00000000e+00 3.07000000e+02]
 [4.91156851e-01 1.00000000e+00 4.80000000e+01]
 [4.78740567e-01 1.00000000e+00 1.00200000e+03]
 [1.00000000e+00 1.98708541e-01 4.20000000e+02]
 [1.00000000e+00 1.51793119e-01 5.480000

In [5]:
for i in range(100):
    f=fitness(pop[:,0], pop[:,1],pop[:,2])
    a=select_mating_pool(pop,f,50) 
    b=a.copy()
    np.random.shuffle(b)
    
    u=np.delete(a,(1,2),1) #b1
    v=np.delete(b,(1,2),1) #b1
    g=np.delete(a,(0,2),1) #b2
    h=np.delete(b,(0,2),1) #b2
    s=np.delete(a,(0,1),1) #d
    t=np.delete(b,(0,1),1) #d



    off_b1 = crossover(get_crossover("real_sbx", prob=0.9, eta=10, prob_per_variable=1.0), u, v)
    off_b2 = crossover(get_crossover("real_sbx", prob=0.9, eta=10, prob_per_variable=1.0), g, h)
    off_d  =  crossover(get_crossover("int_sbx", prob=0.9, eta=10, prob_per_variable=1.0), s, t, xl=2, xu=1100)

    off_b1m = mutation(get_mutation("real_pm", eta=50, prob=0.05), off_b1)
    off_b2m = mutation(get_mutation("real_pm", eta=50, prob=0.05), off_b2)
    off_dm = mutation(get_mutation("int_pm", eta=50, prob=0.5), off_d, xl=2, xu=1100)

    pop=np.concatenate((off_b1m,off_b2m,off_dm),axis=1)
    
    for j in range(pop_size):
        if pop[j][0]>=pop[j][1]:
            pop[j][1]=pop[j][1]/pop[j][0]
            pop[j][0]=1
        else:
            pop[j][0]=pop[j][0]/pop[j][1]
            pop[j][1]=1
    
    best_index=np.argmin(fitness(pop[:,0],pop[:,1],pop[:,2]))
    
    print("gen:",i,"=",pop)
    print("best solution of gen:",i,"=",pop[best_index])


gen: 0 = [[4.35151655e-01 1.00000000e+00 8.00000000e+00]
 [1.00000000e+00 1.51502736e-01 8.84000000e+02]
 [1.20996866e-01 1.00000000e+00 4.38000000e+02]
 [9.54764500e-01 1.00000000e+00 5.74000000e+02]
 [7.66366440e-02 1.00000000e+00 6.10000000e+02]
 [1.00000000e+00 9.86228029e-01 6.73000000e+02]
 [4.88984093e-01 1.00000000e+00 3.37000000e+02]
 [2.17538964e-01 1.00000000e+00 3.98000000e+02]
 [1.00000000e+00 2.61996403e-01 3.63000000e+02]
 [7.44749142e-02 1.00000000e+00 9.50000000e+01]
 [9.63483049e-02 1.00000000e+00 1.77000000e+02]
 [1.82898840e-01 1.00000000e+00 3.82000000e+02]
 [9.94659142e-01 1.00000000e+00 1.09000000e+02]
 [9.98808354e-01 1.00000000e+00 6.04000000e+02]
 [3.31981846e-01 1.00000000e+00 1.79000000e+02]
 [2.12355885e-01 1.00000000e+00 6.38000000e+02]
 [9.38453114e-01 1.00000000e+00 8.00000000e+00]
 [3.64939119e-01 1.00000000e+00 6.51000000e+02]
 [1.44005411e-01 1.00000000e+00 7.03000000e+02]
 [1.58242187e-01 1.00000000e+00 3.08000000e+02]
 [3.44040777e-01 1.00000000e+00

gen: 2 = [[9.18688301e-01 1.00000000e+00 5.29000000e+02]
 [1.80097111e-01 1.00000000e+00 6.98000000e+02]
 [1.00000000e+00 9.84774496e-01 6.40000000e+02]
 [9.99250848e-01 1.00000000e+00 6.18000000e+02]
 [1.14279224e-01 1.00000000e+00 3.65000000e+02]
 [1.16596680e-01 1.00000000e+00 6.01000000e+02]
 [1.00000000e+00 9.96657769e-01 6.57000000e+02]
 [1.00000000e+00 9.98615129e-01 5.64000000e+02]
 [9.99891087e-01 1.00000000e+00 1.14000000e+02]
 [9.91143689e-01 1.00000000e+00 2.44000000e+02]
 [9.85173259e-01 1.00000000e+00 7.11000000e+02]
 [9.83343979e-01 1.00000000e+00 1.29000000e+02]
 [4.99368782e-01 1.00000000e+00 6.45000000e+02]
 [9.79619184e-01 1.00000000e+00 1.35000000e+02]
 [1.00000000e+00 2.52604900e-01 5.66000000e+02]
 [1.00000000e+00 9.57705037e-01 6.41000000e+02]
 [1.13515899e-01 1.00000000e+00 5.79000000e+02]
 [1.91940835e-01 1.00000000e+00 5.66000000e+02]
 [1.38085862e-01 1.00000000e+00 1.30000000e+01]
 [4.42218450e-01 1.00000000e+00 5.60000000e+02]
 [1.95509732e-01 1.00000000e+00

gen: 4 = [[9.83285926e-01 1.00000000e+00 6.60000000e+02]
 [9.97368242e-01 1.00000000e+00 6.17000000e+02]
 [9.93703978e-01 1.00000000e+00 2.48000000e+02]
 [9.81699760e-01 1.00000000e+00 6.24000000e+02]
 [9.92325902e-01 1.00000000e+00 6.27000000e+02]
 [9.94573469e-01 1.00000000e+00 5.29000000e+02]
 [9.95393955e-01 1.00000000e+00 6.06000000e+02]
 [9.99797335e-01 1.00000000e+00 1.75000000e+02]
 [9.90569266e-01 1.00000000e+00 6.08000000e+02]
 [9.90963244e-01 1.00000000e+00 2.74000000e+02]
 [1.00000000e+00 9.77004666e-01 6.03000000e+02]
 [9.78774467e-01 1.00000000e+00 5.72000000e+02]
 [9.97049489e-01 1.00000000e+00 5.73000000e+02]
 [9.96880048e-01 1.00000000e+00 5.68000000e+02]
 [9.98869381e-01 1.00000000e+00 5.94000000e+02]
 [9.97166276e-01 1.00000000e+00 5.77000000e+02]
 [9.97947485e-01 1.00000000e+00 6.30000000e+02]
 [9.99964876e-01 1.00000000e+00 6.19000000e+02]
 [1.00000000e+00 9.99954581e-01 5.82000000e+02]
 [9.96626280e-01 1.00000000e+00 5.71000000e+02]
 [1.00000000e+00 9.97412380e-01

gen: 6 = [[  0.99140584   1.         523.        ]
 [  0.99345361   1.         603.        ]
 [  0.99419924   1.         639.        ]
 [  0.9930186    1.         560.        ]
 [  0.99497962   1.         576.        ]
 [  0.993522     1.         357.        ]
 [  0.99771619   1.         554.        ]
 [  0.99375482   1.         601.        ]
 [  0.99271698   1.         295.        ]
 [  0.99156442   1.         627.        ]
 [  0.99357432   1.         596.        ]
 [  0.99794813   1.         600.        ]
 [  0.98935555   1.         578.        ]
 [  0.99351507   1.         564.        ]
 [  0.99618627   1.         170.        ]
 [  0.99113983   1.         604.        ]
 [  0.99763586   1.          26.        ]
 [  0.99735644   1.         645.        ]
 [  0.99168031   1.         307.        ]
 [  1.           0.99938209 586.        ]
 [  0.99331383   1.         542.        ]
 [  0.99351632   1.         516.        ]
 [  0.98509179   1.         197.        ]
 [  0.99269903   1.      

gen: 8 = [[  0.99243576   1.         647.        ]
 [  0.99276826   1.         628.        ]
 [  0.99189918   1.         571.        ]
 [  0.99257714   1.         596.        ]
 [  0.99355272   1.         568.        ]
 [  0.99321656   1.         593.        ]
 [  0.99312199   1.         332.        ]
 [  0.99275434   1.         565.        ]
 [  0.99352008   1.         608.        ]
 [  0.99311922   1.         565.        ]
 [  0.99252034   1.         599.        ]
 [  0.99170034   1.         648.        ]
 [  0.99270971   1.         582.        ]
 [  0.99363024   1.         438.        ]
 [  0.99351731   1.         215.        ]
 [  0.99347049   1.         260.        ]
 [  0.99073307   1.          56.        ]
 [  0.99344565   1.         641.        ]
 [  0.99340888   1.         609.        ]
 [  0.99414416   1.         625.        ]
 [  0.99252146   1.         562.        ]
 [  0.99323504   1.         444.        ]
 [  0.99292007   1.         569.        ]
 [  0.99316804   1.      

gen: 10 = [[  0.98730181   1.         102.        ]
 [  0.99189544   1.         576.        ]
 [  0.98822907   1.         298.        ]
 [  0.99159038   1.         555.        ]
 [  0.99289971   1.         570.        ]
 [  0.99341899   1.         630.        ]
 [  0.99250517   1.         595.        ]
 [  0.99279241   1.         588.        ]
 [  0.99946508   1.         592.        ]
 [  0.99253692   1.         655.        ]
 [  0.99315398   1.         601.        ]
 [  0.991344     1.         565.        ]
 [  0.99252425   1.         585.        ]
 [  0.99313082   1.         646.        ]
 [  0.99343037   1.         578.        ]
 [  0.99339859   1.         582.        ]
 [  0.99292981   1.         130.        ]
 [  0.99309433   1.         514.        ]
 [  0.99293035   1.         603.        ]
 [  0.99296224   1.         183.        ]
 [  0.99293407   1.         617.        ]
 [  0.99273579   1.         555.        ]
 [  0.99290839   1.         562.        ]
 [  0.99276046   1.     

gen: 12 = [[  0.99309784   1.         561.        ]
 [  0.99174603   1.         551.        ]
 [  0.99252581   1.         587.        ]
 [  0.99255207   1.         538.        ]
 [  0.99293725   1.         576.        ]
 [  0.99971138   1.         593.        ]
 [  0.99290956   1.         559.        ]
 [  0.99286747   1.         591.        ]
 [  0.99278815   1.         592.        ]
 [  0.99298174   1.         596.        ]
 [  0.99281044   1.         560.        ]
 [  0.99322203   1.         606.        ]
 [  0.99272098   1.         616.        ]
 [  0.99254687   1.         541.        ]
 [  0.99252112   1.         647.        ]
 [  0.9924995    1.         584.        ]
 [  0.99243968   1.         564.        ]
 [  0.99279407   1.         590.        ]
 [  0.99261125   1.         566.        ]
 [  0.99292145   1.         568.        ]
 [  0.99319662   1.         569.        ]
 [  0.99283119   1.         619.        ]
 [  0.99321128   1.         560.        ]
 [  0.99318995   1.     

gen: 14 = [[  0.99253377   1.         596.        ]
 [  0.99255667   1.         573.        ]
 [  0.99187918   1.         574.        ]
 [  0.99252584   1.         540.        ]
 [  0.99283573   1.         565.        ]
 [  0.99243866   1.         575.        ]
 [  0.99317294   1.         573.        ]
 [  0.99292096   1.         559.        ]
 [  0.99288629   1.         617.        ]
 [  0.99261434   1.         571.        ]
 [  0.99287667   1.         622.        ]
 [  0.99287207   1.         596.        ]
 [  0.99286587   1.         555.        ]
 [  0.99286747   1.         588.        ]
 [  0.98999663   1.         523.        ]
 [  0.99286663   1.         598.        ]
 [  0.9928423    1.         562.        ]
 [  0.99286446   1.         565.        ]
 [  0.99279085   1.         597.        ]
 [  0.99293775   1.         574.        ]
 [  0.99276374   1.         560.        ]
 [  0.99247261   1.         585.        ]
 [  0.9926088    1.         564.        ]
 [  0.95889553   1.     

gen: 16 = [[  0.99249096   1.         607.        ]
 [  0.99320871   1.         569.        ]
 [  0.99254723   1.         555.        ]
 [  0.99252949   1.         586.        ]
 [  0.99251964   1.         561.        ]
 [  0.9925066    1.         556.        ]
 [  0.992837     1.         557.        ]
 [  0.99287374   1.         573.        ]
 [  0.99290043   1.         607.        ]
 [  0.99320842   1.         593.        ]
 [  0.99251288   1.         559.        ]
 [  0.99285858   1.         575.        ]
 [  0.9927947    1.         592.        ]
 [  0.99255488   1.         567.        ]
 [  0.9928667    1.         548.        ]
 [  0.99286717   1.         551.        ]
 [  0.99371676   1.         581.        ]
 [  0.99256311   1.         552.        ]
 [  0.99286452   1.         588.        ]
 [  0.99285618   1.         608.        ]
 [  0.99286363   1.         556.        ]
 [  0.99286195   1.         562.        ]
 [  0.99285793   1.         654.        ]
 [  0.99284872   1.     

gen: 18 = [[  0.99179201   1.         571.        ]
 [  0.99253137   1.         595.        ]
 [  0.99371255   1.         565.        ]
 [  0.99291222   1.         585.        ]
 [  0.99254085   1.         575.        ]
 [  0.99251218   1.         574.        ]
 [  0.99250688   1.         585.        ]
 [  0.99537068   1.         564.        ]
 [  0.99286731   1.         594.        ]
 [  0.98676388   1.         643.        ]
 [  0.99321661   1.         575.        ]
 [  0.99286989   1.         546.        ]
 [  0.99247512   1.         568.        ]
 [  0.9928734    1.         563.        ]
 [  0.99287089   1.         560.        ]
 [  0.99287402   1.         581.        ]
 [  0.99286537   1.         560.        ]
 [  0.99286435   1.         576.        ]
 [  0.99296446   1.         641.        ]
 [  0.99289903   1.         572.        ]
 [  0.99285784   1.         561.        ]
 [  0.99285497   1.         565.        ]
 [  0.99281783   1.         609.        ]
 [  0.9928805    1.     

gen: 20 = [[  0.99180287   1.         531.        ]
 [  0.99322744   1.         598.        ]
 [  0.99249839   1.         575.        ]
 [  0.9924794    1.         561.        ]
 [  0.9925351    1.         561.        ]
 [  0.99247239   1.         560.        ]
 [  0.99249607   1.         557.        ]
 [  0.9928339    1.         576.        ]
 [  0.99319166   1.         577.        ]
 [  0.99327006   1.         552.        ]
 [  0.99290528   1.         591.        ]
 [  0.99288597   1.         573.        ]
 [  0.99287912   1.         586.        ]
 [  0.9928895    1.         560.        ]
 [  0.99290056   1.         604.        ]
 [  0.99287425   1.         572.        ]
 [  0.99287348   1.         523.        ]
 [  0.99721781   1.         555.        ]
 [  0.99287086   1.         571.        ]
 [  0.99286996   1.         576.        ]
 [  0.99286773   1.         576.        ]
 [  0.99258235   1.         564.        ]
 [  0.97638981   1.         566.        ]
 [  0.99286298   1.     

gen: 22 = [[  0.99797486   1.         570.        ]
 [  0.99257056   1.         554.        ]
 [  0.99251945   1.         588.        ]
 [  0.99287416   1.         585.        ]
 [  0.99249684   1.         576.        ]
 [  0.99287212   1.         547.        ]
 [  0.99247311   1.         562.        ]
 [  0.99257676   1.         541.        ]
 [  0.99248145   1.         598.        ]
 [  0.99246199   1.         610.        ]
 [  0.99286225   1.         572.        ]
 [  0.99288623   1.         535.        ]
 [  0.99286548   1.         564.        ]
 [  0.99287922   1.         560.        ]
 [  0.99287524   1.         590.        ]
 [  0.99287659   1.         564.        ]
 [  0.99280046   1.         594.        ]
 [  0.99288616   1.         554.        ]
 [  0.99256035   1.         510.        ]
 [  0.99288558   1.         594.        ]
 [  0.99287432   1.         489.        ]
 [  0.94630494   1.         567.        ]
 [  0.99287133   1.         548.        ]
 [  0.99287055   1.     

gen: 24 = [[  0.99255143   1.         557.        ]
 [  0.99257955   1.         560.        ]
 [  0.99256667   1.         567.        ]
 [  0.99287318   1.         563.        ]
 [  0.99250157   1.         590.        ]
 [  0.99250574   1.         548.        ]
 [  0.9924649    1.         561.        ]
 [  0.99290818   1.         474.        ]
 [  0.99249347   1.         600.        ]
 [  0.99284806   1.         573.        ]
 [  0.99319096   1.         559.        ]
 [  0.99290634   1.         565.        ]
 [  0.99288077   1.         575.        ]
 [  0.99287962   1.         509.        ]
 [  0.99287581   1.         570.        ]
 [  0.9928778    1.         560.        ]
 [  0.99288839   1.         580.        ]
 [  0.9929055    1.         606.        ]
 [  0.99285734   1.         579.        ]
 [  0.99261183   1.         565.        ]
 [  0.99287513   1.         622.        ]
 [  0.99286771   1.         527.        ]
 [  0.9928746    1.         547.        ]
 [  0.99287475   1.     

gen: 26 = [[  0.9925725    1.         565.        ]
 [  0.99286831   1.         575.        ]
 [  0.99287374   1.         627.        ]
 [  0.99289271   1.         547.        ]
 [  0.99288421   1.         606.        ]
 [  0.99286196   1.         571.        ]
 [  0.99081289   1.         592.        ]
 [  0.99288212   1.         555.        ]
 [  0.99743088   1.         505.        ]
 [  0.99288074   1.         550.        ]
 [  0.99287108   1.         592.        ]
 [  0.99287943   1.         581.        ]
 [  0.99287781   1.         572.        ]
 [  0.99288217   1.         612.        ]
 [  0.9928771    1.         584.        ]
 [  0.99286132   1.         592.        ]
 [  0.9928758    1.         586.        ]
 [  0.99286243   1.         601.        ]
 [  0.99287501   1.         577.        ]
 [  0.99287652   1.         553.        ]
 [  0.99289124   1.         601.        ]
 [  0.99287366   1.         569.        ]
 [  0.99253233   1.         589.        ]
 [  1.           0.99314

gen: 28 = [[  0.99254601   1.         565.        ]
 [  0.99287458   1.         572.        ]
 [  0.99288854   1.         555.        ]
 [  0.99253233   1.         550.        ]
 [  0.99249092   1.         567.        ]
 [  0.99288167   1.         612.        ]
 [  0.99289305   1.         574.        ]
 [  0.9928767    1.         628.        ]
 [  0.99287356   1.         597.        ]
 [  0.99252878   1.         564.        ]
 [  0.99289313   1.         571.        ]
 [  0.99288364   1.         603.        ]
 [  0.99288691   1.         568.        ]
 [  0.99287743   1.         571.        ]
 [  0.9928817    1.         579.        ]
 [  0.99288039   1.         584.        ]
 [  0.99288069   1.         569.        ]
 [  0.99287185   1.         454.        ]
 [  0.99288777   1.         592.        ]
 [  0.98922098   1.         566.        ]
 [  0.99287566   1.         584.        ]
 [  0.99287138   1.         557.        ]
 [  0.99287744   1.         561.        ]
 [  0.99287775   1.     

gen: 30 = [[  0.99256146   1.         559.        ]
 [  0.99255851   1.         578.        ]
 [  1.           0.98303674 558.        ]
 [  0.99287803   1.         564.        ]
 [  0.99289621   1.         599.        ]
 [  0.99289409   1.         575.        ]
 [  0.99287554   1.         573.        ]
 [  0.99289218   1.         571.        ]
 [  0.99287718   1.         625.        ]
 [  0.99288846   1.         591.        ]
 [  0.9928756    1.         652.        ]
 [  0.99288828   1.         564.        ]
 [  0.99255113   1.         590.        ]
 [  0.99287809   1.         550.        ]
 [  0.99290848   1.         543.        ]
 [  0.99287575   1.         564.        ]
 [  0.99287704   1.         657.        ]
 [  0.99288308   1.         512.        ]
 [  0.99288064   1.         576.        ]
 [  0.99287939   1.         599.        ]
 [  0.99287729   1.         585.        ]
 [  0.99287715   1.         561.        ]
 [  0.9928778    1.         585.        ]
 [  0.99287785   1.     

gen: 32 = [[  0.99256569   1.         557.        ]
 [  0.99289146   1.         591.        ]
 [  0.99287356   1.         581.        ]
 [  0.99286949   1.         568.        ]
 [  0.99551962   1.         613.        ]
 [  0.99289527   1.         573.        ]
 [  0.99289261   1.         633.        ]
 [  0.99855087   1.         579.        ]
 [  0.99289465   1.         611.        ]
 [  0.99289328   1.         637.        ]
 [  0.99287855   1.         558.        ]
 [  0.9928882    1.         575.        ]
 [  0.99288802   1.         558.        ]
 [  0.99289282   1.         597.        ]
 [  0.99288769   1.         578.        ]
 [  0.9928838    1.         546.        ]
 [  0.99288629   1.         621.        ]
 [  0.9928768    1.         567.        ]
 [  0.99288768   1.         591.        ]
 [  0.99288386   1.         572.        ]
 [  0.9928774    1.         621.        ]
 [  0.99288837   1.         609.        ]
 [  0.95717586   1.         564.        ]
 [  0.99287811   1.     

gen: 34 = [[  0.99255893   1.         578.        ]
 [  0.99256645   1.         600.        ]
 [  0.99260064   1.         587.        ]
 [  0.98527672   1.         604.        ]
 [  0.99289534   1.         572.        ]
 [  0.9928961    1.         574.        ]
 [  0.99289422   1.         567.        ]
 [  0.99289414   1.         596.        ]
 [  1.           0.99778806 572.        ]
 [  0.99289197   1.         586.        ]
 [  0.99288844   1.         595.        ]
 [  0.99288716   1.         586.        ]
 [  0.99287832   1.         576.        ]
 [  0.99258009   1.         588.        ]
 [  0.99288738   1.         576.        ]
 [  0.99288669   1.         585.        ]
 [  0.99288608   1.         551.        ]
 [  0.9928842    1.         579.        ]
 [  0.99287704   1.         636.        ]
 [  0.99288168   1.         554.        ]
 [  0.99288072   1.         561.        ]
 [  0.99288066   1.         611.        ]
 [  0.99288057   1.         601.        ]
 [  0.99288026   1.     

gen: 36 = [[  0.97144248   1.         602.        ]
 [  0.99255989   1.         574.        ]
 [  0.99254953   1.         622.        ]
 [  0.99250623   1.         581.        ]
 [  0.99288825   1.         585.        ]
 [  0.99289773   1.         582.        ]
 [  0.99287845   1.         567.        ]
 [  0.99287906   1.         559.        ]
 [  0.99289378   1.         537.        ]
 [  0.99289257   1.         590.        ]
 [  0.99289207   1.         676.        ]
 [  0.99288053   1.         601.        ]
 [  0.9928884    1.         624.        ]
 [  0.99287746   1.         606.        ]
 [  0.99247719   1.         587.        ]
 [  0.99287988   1.         595.        ]
 [  0.99288856   1.         567.        ]
 [  0.99258841   1.         551.        ]
 [  0.99288827   1.         574.        ]
 [  0.99288615   1.         576.        ]
 [  1.           0.99590225 557.        ]
 [  0.99288184   1.         581.        ]
 [  0.99288492   1.         591.        ]
 [  0.99288044   1.     

gen: 38 = [[  0.99292421   1.         594.        ]
 [  0.99288019   1.         553.        ]
 [  0.99289515   1.         602.        ]
 [  0.9928976    1.         566.        ]
 [  0.99287766   1.         581.        ]
 [  0.99289394   1.         564.        ]
 [  0.99289354   1.         582.        ]
 [  0.99289272   1.         570.        ]
 [  0.99288034   1.         617.        ]
 [  0.99288028   1.         581.        ]
 [  0.99289177   1.         601.        ]
 [  0.99288918   1.         591.        ]
 [  0.99288886   1.         595.        ]
 [  0.99289504   1.         582.        ]
 [  0.992885     1.         589.        ]
 [  0.99288069   1.         591.        ]
 [  0.99288788   1.         590.        ]
 [  0.99374974   1.         535.        ]
 [  0.99288607   1.         589.        ]
 [  0.99287903   1.         605.        ]
 [  1.           0.99899345 584.        ]
 [  0.99288377   1.         590.        ]
 [  0.99288873   1.         552.        ]
 [  0.99288078   1.     

gen: 40 = [[  0.99289872   1.         570.        ]
 [  0.99289392   1.         582.        ]
 [  0.99289524   1.         579.        ]
 [  0.99288573   1.         603.        ]
 [  0.99287878   1.         566.        ]
 [  0.99288645   1.         592.        ]
 [  0.9928937    1.         582.        ]
 [  0.99289325   1.         627.        ]
 [  0.99288666   1.         568.        ]
 [  0.9928928    1.         578.        ]
 [  0.99288049   1.         620.        ]
 [  0.99288816   1.         559.        ]
 [  0.99289107   1.         550.        ]
 [  0.99289136   1.         593.        ]
 [  0.99288018   1.         558.        ]
 [  0.9928893    1.         548.        ]
 [  0.9928889    1.         569.        ]
 [  0.99287942   1.         595.        ]
 [  0.99288797   1.         623.        ]
 [  0.99288765   1.         615.        ]
 [  0.99288771   1.         533.        ]
 [  0.99288101   1.         531.        ]
 [  0.99288709   1.         572.        ]
 [  0.99288712   1.     

gen: 42 = [[  0.99289689   1.         554.        ]
 [  0.99288767   1.         587.        ]
 [  0.99289467   1.         556.        ]
 [  0.99289413   1.         602.        ]
 [  0.9928933    1.         580.        ]
 [  0.99826751   1.         586.        ]
 [  0.99288652   1.         562.        ]
 [  0.99289288   1.         577.        ]
 [  0.99289233   1.         617.        ]
 [  0.99288656   1.         496.        ]
 [  0.99289298   1.         582.        ]
 [  0.9928934    1.         558.        ]
 [  0.99288152   1.         555.        ]
 [  0.99288817   1.         592.        ]
 [  0.99288801   1.         591.        ]
 [  0.99289307   1.         586.        ]
 [  0.99684638   1.         577.        ]
 [  0.99288814   1.         595.        ]
 [  0.9928874    1.         610.        ]
 [  0.99288731   1.         573.        ]
 [  0.99288591   1.         565.        ]
 [  0.99288653   1.         568.        ]
 [  0.99288682   1.         553.        ]
 [  0.99288698   1.     

gen: 44 = [[  0.99289649   1.         600.        ]
 [  0.9928935    1.         555.        ]
 [  0.99289646   1.         595.        ]
 [  0.99303246   1.         587.        ]
 [  0.99289513   1.         579.        ]
 [  0.97401389   1.         555.        ]
 [  0.9928941    1.         555.        ]
 [  0.99288703   1.         594.        ]
 [  0.99289322   1.         594.        ]
 [  0.99288751   1.         604.        ]
 [  0.99289342   1.         600.        ]
 [  0.99289371   1.         607.        ]
 [  0.99288685   1.         576.        ]
 [  0.99288639   1.         566.        ]
 [  0.99289297   1.         572.        ]
 [  0.99289405   1.         581.        ]
 [  0.99289286   1.         609.        ]
 [  0.99289274   1.         597.        ]
 [  0.99289284   1.         595.        ]
 [  0.9930068    1.         562.        ]
 [  0.99289267   1.         576.        ]
 [  0.99288824   1.         616.        ]
 [  0.99288656   1.         571.        ]
 [  0.99289674   1.     

gen: 46 = [[  0.99289666   1.         657.        ]
 [  0.98461045   1.         590.        ]
 [  0.99289748   1.         568.        ]
 [  0.99289584   1.         638.        ]
 [  0.99289351   1.         606.        ]
 [  0.99289496   1.         560.        ]
 [  0.99289453   1.         585.        ]
 [  0.99289356   1.         579.        ]
 [  0.99289642   1.         620.        ]
 [  0.99289298   1.         580.        ]
 [  0.99289377   1.         577.        ]
 [  0.99289372   1.         605.        ]
 [  0.99289383   1.         581.        ]
 [  0.99289372   1.         567.        ]
 [  0.99289368   1.         568.        ]
 [  0.99289698   1.         591.        ]
 [  0.99289319   1.         576.        ]
 [  0.99289374   1.         582.        ]
 [  0.99289359   1.         574.        ]
 [  0.99289338   1.         589.        ]
 [  0.9928945    1.         601.        ]
 [  0.99289311   1.         560.        ]
 [  0.99289631   1.         592.        ]
 [  0.99289294   1.     

gen: 48 = [[  0.99289803   1.         615.        ]
 [  0.99289778   1.         522.        ]
 [  0.99289346   1.         521.        ]
 [  0.99289401   1.         590.        ]
 [  0.99289482   1.         559.        ]
 [  0.99289377   1.         567.        ]
 [  0.99289634   1.         592.        ]
 [  0.99289633   1.         577.        ]
 [  0.99289479   1.         576.        ]
 [  0.99289368   1.         555.        ]
 [  1.           0.964628   557.        ]
 [  0.99289377   1.         596.        ]
 [  0.99288771   1.         583.        ]
 [  0.99289304   1.         581.        ]
 [  0.9928938    1.         572.        ]
 [  0.99289372   1.         577.        ]
 [  0.99289822   1.         575.        ]
 [  0.99289374   1.         576.        ]
 [  0.99289373   1.         592.        ]
 [  0.99289368   1.         569.        ]
 [  0.99634875   1.         592.        ]
 [  0.99289352   1.         585.        ]
 [  0.9928937    1.         561.        ]
 [  0.9928879    1.     

gen: 50 = [[  1.           0.95408391 637.        ]
 [  0.99289684   1.         573.        ]
 [  0.99289746   1.         592.        ]
 [  0.9998686    1.         570.        ]
 [  0.99289683   1.         568.        ]
 [  0.99686962   1.         588.        ]
 [  0.99289635   1.         590.        ]
 [  0.99330855   1.         582.        ]
 [  0.99289502   1.         593.        ]
 [  0.99289497   1.         595.        ]
 [  0.99330977   1.         594.        ]
 [  0.99289473   1.         560.        ]
 [  0.99289358   1.         584.        ]
 [  0.99289403   1.         602.        ]
 [  0.99289377   1.         589.        ]
 [  0.99289391   1.         572.        ]
 [  0.97115715   1.         628.        ]
 [  0.9928938    1.         586.        ]
 [  0.99289229   1.         595.        ]
 [  0.99289376   1.         568.        ]
 [  0.99289311   1.         568.        ]
 [  0.99289272   1.         523.        ]
 [  0.99289374   1.         583.        ]
 [  0.99289373   1.     

gen: 52 = [[  0.99289374   1.         511.        ]
 [  0.99289484   1.         611.        ]
 [  0.99289763   1.         566.        ]
 [  0.99289381   1.         586.        ]
 [  0.99289772   1.         616.        ]
 [  0.99289654   1.         610.        ]
 [  0.9928968    1.         587.        ]
 [  0.99289663   1.         619.        ]
 [  0.9928948    1.         476.        ]
 [  0.99289496   1.         592.        ]
 [  0.94697696   1.         639.        ]
 [  0.99289597   1.         619.        ]
 [  0.99289504   1.         605.        ]
 [  0.99954039   1.         566.        ]
 [  0.99289383   1.         591.        ]
 [  0.99289354   1.         566.        ]
 [  0.99289375   1.         570.        ]
 [  0.99289472   1.         567.        ]
 [  0.9928936    1.         576.        ]
 [  0.99289351   1.         627.        ]
 [  0.99289391   1.         568.        ]
 [  0.99289376   1.         592.        ]
 [  0.99289386   1.         575.        ]
 [  0.9928937    1.     

gen: 54 = [[  0.99289452   1.         570.        ]
 [  0.99289775   1.         589.        ]
 [  0.99289734   1.         602.        ]
 [  0.99289682   1.         570.        ]
 [  0.9928968    1.         610.        ]
 [  0.992894     1.         564.        ]
 [  0.99289706   1.         584.        ]
 [  0.99289686   1.         587.        ]
 [  0.99289503   1.         581.        ]
 [  0.99289655   1.         620.        ]
 [  0.99289384   1.         543.        ]
 [  0.99289633   1.         584.        ]
 [  0.99289648   1.         539.        ]
 [  0.99289397   1.         567.        ]
 [  0.99289639   1.         575.        ]
 [  0.99289631   1.         537.        ]
 [  0.99289624   1.         558.        ]
 [  0.99305469   1.         573.        ]
 [  0.99289374   1.         561.        ]
 [  0.99289379   1.         566.        ]
 [  0.99289508   1.         607.        ]
 [  0.99289638   1.         607.        ]
 [  0.99289664   1.         507.        ]
 [  0.99289485   1.     

gen: 56 = [[  0.97785428   1.         596.        ]
 [  0.99289791   1.         600.        ]
 [  0.99289702   1.         552.        ]
 [  0.99289644   1.         562.        ]
 [  0.99289394   1.         582.        ]
 [  0.99289685   1.         552.        ]
 [  0.992895     1.         569.        ]
 [  0.99289504   1.         607.        ]
 [  0.99289605   1.         575.        ]
 [  0.99289636   1.         600.        ]
 [  0.99289395   1.         610.        ]
 [  0.99289372   1.         603.        ]
 [  0.99289622   1.         632.        ]
 [  0.99289691   1.         616.        ]
 [  0.99289788   1.         575.        ]
 [  0.99289709   1.         653.        ]
 [  0.99289641   1.         572.        ]
 [  0.99289415   1.         557.        ]
 [  0.9928961    1.         606.        ]
 [  0.99289613   1.         539.        ]
 [  0.9928962    1.         597.        ]
 [  0.99289381   1.         557.        ]
 [  0.99289512   1.         608.        ]
 [  0.99289498   1.     

gen: 58 = [[  0.9986722    1.         608.        ]
 [  0.99289657   1.         568.        ]
 [  0.9928972    1.         624.        ]
 [  0.99289385   1.         590.        ]
 [  0.99895452   1.         553.        ]
 [  0.99289621   1.         608.        ]
 [  0.99289659   1.         557.        ]
 [  0.99289677   1.         580.        ]
 [  0.99289645   1.         623.        ]
 [  0.99289609   1.         604.        ]
 [  0.99289393   1.         586.        ]
 [  0.99289643   1.         558.        ]
 [  0.99289648   1.         600.        ]
 [  0.99289374   1.         630.        ]
 [  0.99289616   1.         592.        ]
 [  0.99289636   1.         601.        ]
 [  0.99289646   1.         565.        ]
 [  0.99289375   1.         562.        ]
 [  0.99671555   1.         600.        ]
 [  0.99289396   1.         574.        ]
 [  0.99289621   1.         573.        ]
 [  0.99289644   1.         586.        ]
 [  0.99289478   1.         581.        ]
 [  1.           0.99845

gen: 60 = [[  0.94622935   1.         555.        ]
 [  0.99289684   1.         593.        ]
 [  0.99289648   1.         582.        ]
 [  0.99289684   1.         573.        ]
 [  0.99289634   1.         582.        ]
 [  0.99289607   1.         554.        ]
 [  0.99289656   1.         551.        ]
 [  0.99289686   1.         502.        ]
 [  0.99289648   1.         553.        ]
 [  0.99289385   1.         600.        ]
 [  0.99289647   1.         590.        ]
 [  0.99289645   1.         582.        ]
 [  0.9928967    1.         600.        ]
 [  0.99289645   1.         568.        ]
 [  0.99289635   1.         595.        ]
 [  0.99289396   1.         592.        ]
 [  0.99539519   1.         655.        ]
 [  0.9928962    1.         580.        ]
 [  0.99289401   1.         582.        ]
 [  0.99289617   1.         660.        ]
 [  0.96734392   1.         582.        ]
 [  0.99289616   1.         605.        ]
 [  0.99289618   1.         547.        ]
 [  0.99289613   1.     

gen: 62 = [[  0.9928981    1.         541.        ]
 [  0.99289807   1.         558.        ]
 [  0.99289366   1.         601.        ]
 [  0.99289672   1.         557.        ]
 [  0.9879121    1.         546.        ]
 [  0.99289664   1.         593.        ]
 [  0.99289657   1.         595.        ]
 [  0.99289649   1.         573.        ]
 [  0.99289648   1.         617.        ]
 [  1.           0.99566991 588.        ]
 [  0.99289513   1.         630.        ]
 [  0.99289388   1.         572.        ]
 [  0.99289408   1.         590.        ]
 [  0.99289638   1.         593.        ]
 [  0.99289362   1.         577.        ]
 [  0.99289618   1.         567.        ]
 [  0.99289641   1.         592.        ]
 [  0.99289386   1.         591.        ]
 [  0.992896     1.         590.        ]
 [  0.99289635   1.         570.        ]
 [  0.9928966    1.         585.        ]
 [  0.99289511   1.         596.        ]
 [  0.99289499   1.         579.        ]
 [  0.93831302   1.     

gen: 64 = [[  0.99289671   1.         597.        ]
 [  0.99289465   1.         579.        ]
 [  0.99289746   1.         596.        ]
 [  0.99289686   1.         631.        ]
 [  0.99289684   1.         626.        ]
 [  0.99289639   1.         557.        ]
 [  0.99289678   1.         629.        ]
 [  0.99289699   1.         552.        ]
 [  0.99289673   1.         551.        ]
 [  0.99289646   1.         566.        ]
 [  0.99289622   1.         586.        ]
 [  0.99289667   1.         553.        ]
 [  0.99289681   1.         614.        ]
 [  0.99289658   1.         601.        ]
 [  0.99289645   1.         551.        ]
 [  0.99289657   1.         638.        ]
 [  0.99289633   1.         593.        ]
 [  0.99289674   1.         601.        ]
 [  0.99289647   1.         536.        ]
 [  0.99289646   1.         572.        ]
 [  0.99289398   1.         567.        ]
 [  1.           0.93806916 586.        ]
 [  0.99289628   1.         553.        ]
 [  0.99289657   1.     

gen: 66 = [[  0.99289592   1.         600.        ]
 [  0.99289612   1.         558.        ]
 [  0.99289754   1.         601.        ]
 [  0.98936546   1.         596.        ]
 [  0.99289672   1.         570.        ]
 [  0.99289666   1.         554.        ]
 [  0.99289664   1.         552.        ]
 [  0.99289656   1.         547.        ]
 [  0.99289637   1.         519.        ]
 [  0.99289657   1.         551.        ]
 [  0.99289656   1.         582.        ]
 [  0.99289659   1.         595.        ]
 [  0.99289622   1.         570.        ]
 [  0.99289647   1.         580.        ]
 [  0.9928959    1.         600.        ]
 [  0.99289645   1.         531.        ]
 [  0.99289639   1.         558.        ]
 [  0.99289642   1.         601.        ]
 [  0.99289616   1.         602.        ]
 [  0.99289642   1.         530.        ]
 [  0.99289654   1.         591.        ]
 [  0.99289746   1.         596.        ]
 [  0.99289619   1.         602.        ]
 [  0.99289633   1.     

gen: 68 = [[  0.9928986    1.         600.        ]
 [  0.99289629   1.         619.        ]
 [  0.99289754   1.         594.        ]
 [  1.           0.96928307 482.        ]
 [  0.99289679   1.         529.        ]
 [  0.99289628   1.         587.        ]
 [  0.99289667   1.         627.        ]
 [  0.99289625   1.         588.        ]
 [  0.99289663   1.         612.        ]
 [  0.99289662   1.         601.        ]
 [  0.99289662   1.         587.        ]
 [  0.99289657   1.         572.        ]
 [  0.99289871   1.         610.        ]
 [  0.99289625   1.         595.        ]
 [  0.99289658   1.         572.        ]
 [  0.99289626   1.         580.        ]
 [  0.99289656   1.         589.        ]
 [  0.9928965    1.         555.        ]
 [  0.99289643   1.         611.        ]
 [  0.99289645   1.         559.        ]
 [  0.99289644   1.         601.        ]
 [  0.99289631   1.         574.        ]
 [  0.99289618   1.         616.        ]
 [  0.99289643   1.     

gen: 70 = [[  0.99289937   1.         570.        ]
 [  0.99289856   1.         606.        ]
 [  0.9928975    1.         551.        ]
 [  0.99289673   1.         582.        ]
 [  1.           0.99346755 589.        ]
 [  0.99289635   1.         601.        ]
 [  0.99289636   1.         557.        ]
 [  1.           0.97809447 562.        ]
 [  0.99289664   1.         577.        ]
 [  0.99289664   1.         608.        ]
 [  0.99289657   1.         558.        ]
 [  0.99289641   1.         576.        ]
 [  0.99289661   1.         517.        ]
 [  0.99289658   1.         581.        ]
 [  0.99289657   1.         574.        ]
 [  0.99289657   1.         592.        ]
 [  0.99289657   1.         602.        ]
 [  0.99289658   1.         586.        ]
 [  0.99289643   1.         597.        ]
 [  0.99289654   1.         601.        ]
 [  0.99289645   1.         522.        ]
 [  0.98616756   1.         585.        ]
 [  0.99289643   1.         598.        ]
 [  0.99289643   1.     

gen: 72 = [[  0.9928963    1.         567.        ]
 [  0.99289844   1.         591.        ]
 [  0.99289635   1.         573.        ]
 [  0.99289633   1.         546.        ]
 [  0.99289672   1.         562.        ]
 [  0.99289669   1.         595.        ]
 [  0.99289671   1.         597.        ]
 [  0.99289657   1.         591.        ]
 [  0.99289666   1.         561.        ]
 [  0.99289641   1.         596.        ]
 [  0.99289661   1.         601.        ]
 [  0.99289646   1.         573.        ]
 [  1.           0.98942419 591.        ]
 [  0.99051956   1.         554.        ]
 [  0.99289667   1.         449.        ]
 [  0.9928966    1.         585.        ]
 [  0.99289659   1.         595.        ]
 [  0.99289656   1.         594.        ]
 [  0.99289659   1.         506.        ]
 [  0.99289658   1.         596.        ]
 [  0.99289653   1.         600.        ]
 [  0.99289654   1.         649.        ]
 [  0.99289654   1.         589.        ]
 [  0.99289654   1.     

gen: 74 = [[  0.99289926   1.         600.        ]
 [  0.99289927   1.         574.        ]
 [  0.99289657   1.         562.        ]
 [  0.99289611   1.         596.        ]
 [  0.99289676   1.         601.        ]
 [  0.99289673   1.         586.        ]
 [  0.99289671   1.         560.        ]
 [  0.99289669   1.         602.        ]
 [  0.99289671   1.         572.        ]
 [  0.99289673   1.         623.        ]
 [  0.99289668   1.         583.        ]
 [  0.99289666   1.         586.        ]
 [  0.99289671   1.         591.        ]
 [  0.99289661   1.         592.        ]
 [  0.99289663   1.         578.        ]
 [  0.99289661   1.         554.        ]
 [  0.99289661   1.         602.        ]
 [  0.99289658   1.         603.        ]
 [  0.9928966    1.         595.        ]
 [  0.99289673   1.         564.        ]
 [  0.99289659   1.         623.        ]
 [  0.9928984    1.         592.        ]
 [  0.99289671   1.         571.        ]
 [  0.99289656   1.     

gen: 76 = [[  0.99289956   1.         606.        ]
 [  0.99289954   1.         600.        ]
 [  0.99289943   1.         595.        ]
 [  0.9928989    1.         562.        ]
 [  0.992899     1.         618.        ]
 [  0.99289954   1.         604.        ]
 [  0.9928984    1.         568.        ]
 [  0.99289682   1.         564.        ]
 [  0.99289677   1.         579.        ]
 [  0.99289682   1.         565.        ]
 [  0.99289676   1.         602.        ]
 [  0.99289663   1.         590.        ]
 [  0.99289676   1.         567.        ]
 [  0.99289671   1.         571.        ]
 [  0.99289671   1.         597.        ]
 [  0.99289671   1.         590.        ]
 [  0.99289664   1.         591.        ]
 [  0.98982239   1.         594.        ]
 [  1.           0.99672915 564.        ]
 [  0.99289636   1.         605.        ]
 [  0.9928986    1.         576.        ]
 [  0.99289664   1.         570.        ]
 [  0.99289663   1.         548.        ]
 [  0.99289665   1.     

gen: 78 = [[  0.99289951   1.         609.        ]
 [  0.99289936   1.         535.        ]
 [  0.99289901   1.         560.        ]
 [  0.99289671   1.         593.        ]
 [  0.99289687   1.         559.        ]
 [  0.99289683   1.         562.        ]
 [  0.9928968    1.         559.        ]
 [  0.99289678   1.         614.        ]
 [  0.99854507   1.         526.        ]
 [  0.99289682   1.         547.        ]
 [  0.99289675   1.         566.        ]
 [  0.99289674   1.         554.        ]
 [  0.99289674   1.         558.        ]
 [  0.99289672   1.         584.        ]
 [  0.99289672   1.         538.        ]
 [  0.99289672   1.         608.        ]
 [  0.99289656   1.         591.        ]
 [  0.99289651   1.         623.        ]
 [  0.99289671   1.         507.        ]
 [  0.9928967    1.         591.        ]
 [  0.99289676   1.         568.        ]
 [  0.99289666   1.         566.        ]
 [  0.99289678   1.         584.        ]
 [  0.99289657   1.     

gen: 80 = [[  0.9928992    1.         590.        ]
 [  0.99289872   1.         582.        ]
 [  0.99289704   1.         595.        ]
 [  0.99289693   1.         546.        ]
 [  0.99289867   1.         571.        ]
 [  0.99289676   1.         567.        ]
 [  0.99289694   1.         575.        ]
 [  0.99289665   1.         562.        ]
 [  0.99289666   1.         554.        ]
 [  0.99289682   1.         555.        ]
 [  0.99289664   1.         559.        ]
 [  0.99289677   1.         585.        ]
 [  0.99289675   1.         578.        ]
 [  0.99289677   1.         552.        ]
 [  0.99289678   1.         564.        ]
 [  0.99289675   1.         582.        ]
 [  0.99289677   1.         554.        ]
 [  0.99289674   1.         575.        ]
 [  0.99289675   1.         585.        ]
 [  0.99289674   1.         559.        ]
 [  0.99289671   1.         596.        ]
 [  0.99289671   1.         591.        ]
 [  0.99289884   1.         582.        ]
 [  0.95284115   1.     

gen: 82 = [[  0.9928993    1.         546.        ]
 [  0.99289657   1.         563.        ]
 [  0.99289867   1.         561.        ]
 [  0.99289674   1.         615.        ]
 [  0.99289878   1.         587.        ]
 [  0.99289658   1.         553.        ]
 [  0.99289692   1.         567.        ]
 [  0.99289691   1.         581.        ]
 [  0.99289687   1.         580.        ]
 [  0.99289685   1.         561.        ]
 [  0.99289679   1.         518.        ]
 [  0.99289679   1.         570.        ]
 [  0.99716272   1.         601.        ]
 [  0.99289678   1.         572.        ]
 [  0.99289678   1.         559.        ]
 [  0.99289666   1.         577.        ]
 [  0.99289677   1.         564.        ]
 [  0.99289678   1.         608.        ]
 [  0.99289677   1.         558.        ]
 [  0.99289677   1.         542.        ]
 [  0.994506     1.         568.        ]
 [  0.9928967    1.         567.        ]
 [  0.99289686   1.         531.        ]
 [  0.99289672   1.     

gen: 84 = [[  0.99289873   1.         581.        ]
 [  0.99289875   1.         585.        ]
 [  0.99289672   1.         629.        ]
 [  0.99289699   1.         567.        ]
 [  0.9928968    1.         572.        ]
 [  0.9928969    1.         563.        ]
 [  0.99289689   1.         581.        ]
 [  0.99289677   1.         596.        ]
 [  0.99289679   1.         532.        ]
 [  0.99289678   1.         598.        ]
 [  0.99289678   1.         558.        ]
 [  0.99289678   1.         590.        ]
 [  0.99340369   1.         573.        ]
 [  0.99289881   1.         587.        ]
 [  0.99289677   1.         566.        ]
 [  0.98146336   1.         565.        ]
 [  0.99289666   1.         600.        ]
 [  0.99289677   1.         601.        ]
 [  0.9928989    1.         545.        ]
 [  0.99289678   1.         548.        ]
 [  0.99289664   1.         560.        ]
 [  0.99289859   1.         628.        ]
 [  0.99289672   1.         621.        ]
 [  0.99289671   1.     

gen: 86 = [[  0.99289883   1.         573.        ]
 [  0.9928989    1.         558.        ]
 [  0.99289669   1.         589.        ]
 [  0.99289864   1.         550.        ]
 [  0.99289863   1.         587.        ]
 [  0.99289866   1.         560.        ]
 [  0.99289678   1.         569.        ]
 [  0.99289675   1.         590.        ]
 [  0.99289691   1.         569.        ]
 [  0.99289899   1.         582.        ]
 [  0.99289677   1.         556.        ]
 [  0.99289644   1.         597.        ]
 [  0.99289666   1.         576.        ]
 [  0.99289687   1.         556.        ]
 [  0.99289686   1.         550.        ]
 [  0.99289682   1.         580.        ]
 [  0.9928968    1.         610.        ]
 [  0.99289679   1.         550.        ]
 [  0.99289679   1.         625.        ]
 [  0.99289678   1.         560.        ]
 [  0.9928987    1.         600.        ]
 [  0.99289678   1.         578.        ]
 [  0.99289677   1.         602.        ]
 [  0.99289668   1.     

gen: 88 = [[  0.99289648   1.         606.        ]
 [  0.99289877   1.         589.        ]
 [  0.99289885   1.         541.        ]
 [  0.99289883   1.         550.        ]
 [  0.9928988    1.         616.        ]
 [  0.99289676   1.         596.        ]
 [  0.99289669   1.         656.        ]
 [  0.99289844   1.         587.        ]
 [  0.99289817   1.         576.        ]
 [  0.99289907   1.         555.        ]
 [  0.99289698   1.         573.        ]
 [  0.99289697   1.         591.        ]
 [  0.99289697   1.         626.        ]
 [  0.99289694   1.         611.        ]
 [  0.99289692   1.         591.        ]
 [  0.99289665   1.         578.        ]
 [  0.99289687   1.         601.        ]
 [  1.           0.9744198  573.        ]
 [  0.99289687   1.         571.        ]
 [  0.9928967    1.         513.        ]
 [  0.99289681   1.         577.        ]
 [  0.99289665   1.         563.        ]
 [  0.99289885   1.         596.        ]
 [  0.99289695   1.     

gen: 90 = [[  0.99289689   1.         632.        ]
 [  0.99289902   1.         577.        ]
 [  0.99289865   1.         577.        ]
 [  0.99289872   1.         619.        ]
 [  0.99289669   1.         553.        ]
 [  0.99289686   1.         598.        ]
 [  0.99289851   1.         569.        ]
 [  0.99289841   1.         581.        ]
 [  0.99289681   1.         577.        ]
 [  0.99289833   1.         635.        ]
 [  0.89651937   1.         582.        ]
 [  0.99289725   1.         602.        ]
 [  0.99289707   1.         577.        ]
 [  0.99289683   1.         576.        ]
 [  0.992897     1.         616.        ]
 [  0.99289687   1.         572.        ]
 [  0.99289684   1.         605.        ]
 [  0.99289687   1.         590.        ]
 [  0.99289676   1.         571.        ]
 [  0.99289688   1.         562.        ]
 [  0.99289667   1.         540.        ]
 [  0.99289676   1.         547.        ]
 [  0.99289702   1.         571.        ]
 [  0.99289688   1.     

gen: 92 = [[  0.9928991    1.         576.        ]
 [  0.99289909   1.         572.        ]
 [  0.99289705   1.         577.        ]
 [  0.99289905   1.         594.        ]
 [  0.99289907   1.         605.        ]
 [  0.99289841   1.         587.        ]
 [  0.99450744   1.         573.        ]
 [  0.99289695   1.         566.        ]
 [  0.95339922   1.         611.        ]
 [  0.99289847   1.         599.        ]
 [  0.99289858   1.         619.        ]
 [  0.99289847   1.         586.        ]
 [  0.99289846   1.         563.        ]
 [  0.99289703   1.         577.        ]
 [  0.9928969    1.         613.        ]
 [  0.99289905   1.         512.        ]
 [  0.99289702   1.         576.        ]
 [  0.9928986    1.         552.        ]
 [  0.99289691   1.         577.        ]
 [  0.98960161   1.         576.        ]
 [  0.99289895   1.         599.        ]
 [  0.99289693   1.         568.        ]
 [  0.99289694   1.         576.        ]
 [  0.99289688   1.     

gen: 94 = [[  0.99289913   1.         579.        ]
 [  0.99289678   1.         593.        ]
 [  0.99289701   1.         639.        ]
 [  0.99289681   1.         576.        ]
 [  0.99289897   1.         581.        ]
 [  0.99289888   1.         576.        ]
 [  0.99289842   1.         617.        ]
 [  0.99289725   1.         562.        ]
 [  0.99289693   1.         571.        ]
 [  0.99289861   1.         590.        ]
 [  0.99289862   1.         563.        ]
 [  0.99289857   1.         576.        ]
 [  0.99289852   1.         561.        ]
 [  0.99289693   1.         635.        ]
 [  0.99289842   1.         564.        ]
 [  0.99289845   1.         592.        ]
 [  0.99289707   1.         586.        ]
 [  0.99289706   1.         568.        ]
 [  0.99289706   1.         572.        ]
 [  0.99245803   1.         571.        ]
 [  0.99289838   1.         563.        ]
 [  0.99289848   1.         580.        ]
 [  0.99289693   1.         581.        ]
 [  0.99289702   1.     

gen: 96 = [[  0.99289695   1.         587.        ]
 [  0.99289954   1.         596.        ]
 [  0.99289916   1.         583.        ]
 [  0.99289691   1.         503.        ]
 [  0.99289693   1.         563.        ]
 [  0.98835619   1.         585.        ]
 [  0.99289897   1.         586.        ]
 [  0.99289902   1.         581.        ]
 [  0.99289708   1.         627.        ]
 [  0.99289851   1.         647.        ]
 [  0.99289885   1.         532.        ]
 [  0.99289881   1.         605.        ]
 [  0.99289867   1.         563.        ]
 [  0.99289873   1.         594.        ]
 [  0.99289864   1.         562.        ]
 [  0.99289711   1.         580.        ]
 [  0.99289854   1.         594.        ]
 [  0.99289852   1.         592.        ]
 [  0.99289843   1.         541.        ]
 [  0.99672319   1.         578.        ]
 [  0.99289837   1.         602.        ]
 [  0.99289695   1.         571.        ]
 [  0.99289827   1.         586.        ]
 [  0.99289726   1.     

gen: 98 = [[  0.99289959   1.         576.        ]
 [  0.99289958   1.         575.        ]
 [  0.99289704   1.         589.        ]
 [  0.99745951   1.         595.        ]
 [  0.99289884   1.         606.        ]
 [  0.99289915   1.         559.        ]
 [  0.99289906   1.         620.        ]
 [  0.99289707   1.         560.        ]
 [  0.99289908   1.         563.        ]
 [  0.99289903   1.         561.        ]
 [  1.           0.9808159  634.        ]
 [  0.99289904   1.         562.        ]
 [  0.99289905   1.         552.        ]
 [  0.99289942   1.         621.        ]
 [  0.99289855   1.         546.        ]
 [  0.99289883   1.         570.        ]
 [  0.99289885   1.         561.        ]
 [  0.99289878   1.         577.        ]
 [  0.99289878   1.         576.        ]
 [  0.99289825   1.         592.        ]
 [  0.99289868   1.         554.        ]
 [  0.99289867   1.         666.        ]
 [  0.99289866   1.         573.        ]
 [  1.           0.99838

In [11]:
b1=pop[best_index][0]
b2=pop[best_index][1]
d= pop[best_index][2]
d= d.astype(int)
print("b1=",b1,"b2=",b2,"d=",d)

c  = np.array((phi1**b1)*(phi2**b2))
X  =((c.max()-c.min())/d)


y=np.full((d,1100), np.nan)
for j in range(d-1):
    y[j,:c[np.logical_and(c>=j*X+c.min(),c<(j+1)*X+c.min())].size]=c[np.logical_and(c>=j*X+c.min(),c<(j+1)*X+c.min())]
y[d-1,:c[np.logical_and(c>=(d-1)*X+c.min(),c<=c.max())].size]=c[np.logical_and(c>=(d-1)*X+c.min(),c<=c.max())]

p=np.copy(y)



import math
C_=0
U_=0

count1= np.count_nonzero(~np.isnan(p[0]))
if count1<= (math.floor(1100/d)+3) :
    U_=U_+count1
else :
    C_=C_+1

for k in range (1,d):
    count= np.count_nonzero(~np.isnan(p[k]))
    count_=np.count_nonzero(~np.isnan(p[k-1]))

    if count<= (math.floor(1100/d)+3) :
        U_=U_+count
    elif count_<=(math.floor(1100/d)+3) :
        C_=C_+1
    else:
        p[k][count:count+count_]=p[k-1][:count_]
        p[k-1]= np.full((1,1100), np.nan)
        
Significance= (1100-U_)/11
print("Significance percentage =",Significance,"%")


b1= 0.9929210123530718 b2= 1.0 d= 573
Significance percentage = 83.45454545454545 %
